🚀 3단계 - 요금 정책 추가Step3
next-step/atdd-subway-time pull request #484
Opened 2024-03-18 08:04 UTC by hhhhhwi

안녕하세요 성현님 🙇 
3단계 PR 올립니다..!

2024-03-18 08:08 UTC, hhhhhwi commented on src/test/java/nextstep/subway/acceptance/FavoriteAcceptanceTest.java
> +		LineSteps.노선_생성_요청("분당선", "노랑", 종로3가역, 시청역, 6, 4, 0);
요구사항을 적용하며 변수를 하나 더 선언하게 되면, 코드 수정을 해야되는 부분이 많아지더라구요 ㅠ 특히나 테스트 코드 중 생성자를 많이 사용하다보니, 더 그렇게 느껴지는 것 같습니다..! 제가 픽스쳐 관리를 잘 못 하고 있는걸까요..?

2024-03-18 08:14 UTC, hhhhhwi commented on src/main/java/nextstep/subway/domain/SubwayMapByDistance.java
> +	private final SubwayMap subwayMap;
지난번 피드백을 참고하여 조합으로 구현해보았습니다! 
SubwayMapBy~ 객체들은 is-A 구조이지 않을까? 라는 생각으로 상속으로 구혔했었는데, 
조합으로 구현하니 변화에 좀 더 유연하게 대처할 수 있는 객체가 된 것 같습니다..!

혹시 성현님은 상속과 조합 중에 구현 방식을 선택하는 기준이 따로 있으신가요?

2024-03-18 08:26 UTC, hhhhhwi commented
> 지금도 좋지만! 궁금한 점!
SubwayMap 생성자 대신 Factory를 별도로 만들어 준 이유가 있나요?

저번 피드백 때 주셨던 질문에 지금 답변을 드리자면!

객체 생성에 대한 기준이 있어 따로 생성 객체를 분리해야 되는 경우,
기준이 간단하거나 한가지만 있을 경우에 주로 Factory 패턴을 적용하는 편입니다..!

2024-03-21 01:01 UTC, boorownie commented on src/test/java/nextstep/subway/acceptance/FavoriteAcceptanceTest.java
> +		LineSteps.노선_생성_요청("분당선", "노랑", 종로3가역, 시청역, 6, 4, 0);
자연스러운 현상입니다. 
이런 경우 기본 값을 이용하여 번거로운 코드 작업을 방지하는 방법이 있는데요
기본 값을 지정하되, builder 패턴 등을 이용해서 필요한 부부만 수정해서 활용하는 방법이 있습니다.

2024-03-21 01:15 UTC, boorownie commented on src/main/java/nextstep/subway/domain/SubwayMapByDistance.java
> +	private final SubwayMap subwayMap;
저는 가급적 조합을 활용해서 구현하는 편이에요! 선호의 차이일 수 있지만 상속 방법 보다는 조합 방법이 조금 더 유연한 것 같아서요~

2024-03-21 01:52 UTC, boorownie requested changes
안녕하세요. 요근래 일정이 바빠서 리뷰가 늦었네요ㅠㅠ
3단계 요구사항을 충분히 충족해주셨지만 몇가지 도움될 수 있는 코멘트를 남겼습니다.
확인해주시고 반영 여부 판단해서 재요청 부탁드립니다~

2024-03-21 01:52 UTC, boorownie commented on src/test/resources/features/line.feature
> +      | 삼호선 | 주황  |     도곡역    |    개포동역  |     4    |    5     |    0     |
반복되는 스텝은 Background를 활용할 수 있어요!
각 스텝을 시나리오에서 분리하는 것에 대해서는 취향에 따라 다르게 생각할 수 있으니 참고만 해주세요~

2024-03-21 01:52 UTC, boorownie commented on src/test/java/nextstep/subway/unit/FareCalculatorTest.java
> +    void whenLineHasAdditionalFeeThenCalculateFareWithMaxFee() {
테스트를 작성하면서 문서화의 효과도 가져갈 수 있어 좋네요 👍

2024-03-21 01:52 UTC, boorownie commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +	private Long get노선Id(ExtractableResponse<Response> response) {
네이밍이ㅋㅋㅋ getLineId를 의미하신걸까요?ㅋㅋㅋ

2024-03-21 01:52 UTC, boorownie commented on src/main/java/nextstep/auth/AuthenticationPrincipalArgumentResolver.java
> +            }
선택적 예외처리 👍

2024-03-21 01:52 UTC, boorownie commented on src/main/java/nextstep/auth/domain/NonLoginMember.java
> +public class NonLoginMember extends LoginMember{
널오브젝트 패턴 적용 👍

2024-03-21 01:52 UTC, boorownie commented on src/main/java/nextstep/subway/ui/controller/PathController.java
> +		}
널 오브젝트 패턴의 장점은 호출 하는 당시에는 분기 처리를 하지 않아도 되는 점이에요!
loginMember를 넘겨주어 분기처리(if문)을 제거해보세요~

2024-03-21 01:52 UTC, boorownie commented on src/main/java/nextstep/subway/application/service/PathService.java
> +	}
이 두 메서드도 하나로 묶을 방법이 없을지 고민해보면 좋겠어요~

2024-03-21 01:52 UTC, boorownie commented on src/main/java/nextstep/subway/domain/FareCalculator.java
> +            fare *= 1 - policy.getDiscountPercent();
'+', '-'과 같은 operation정보도 FareCalculator 코드에 있는게 아니라 각 policy의 상태로 가지고 있으면 좋겠네요 :)

2024-03-21 01:52 UTC, boorownie commented on src/main/java/nextstep/subway/domain/FareCalculator.java
>  public class FareCalculator {
FarePolicy들을 관리하고 계산하는 구조를 잘 설계하신 것 같습니다 👍

2024-03-21 01:52 UTC, boorownie commented on src/main/java/nextstep/subway/domain/FareCalculator.java
> +        this.fare = 1250;
기본 요금의 의미가 더 드러나게 상수 값으로 지정하면 어떨까요?

2024-03-22 10:19 UTC, hhhhhwi commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +	private Long get노선Id(ExtractableResponse<Response> response) {
ㅋㅋㅋㅋㅋㅋㅋㅋ 아 제가.. 정신을 어디다 버리고 왔었나봐욬ㅋㅋㅋㅋㅋㅋㅋ 저도 보고 깜짝 놀랬습니다;

2024-03-22 15:08 UTC, hhhhhwi commented on src/main/java/nextstep/subway/domain/FareCalculator.java
> +            fare *= 1 - policy.getDiscountPercent();
메소드 자체가 operation 정보를 갖고 있다고 생각하여 상태값으로 관리하지 않고 메소드 안에서 fare에 할인을 적용하는 방식으로 수정해보았습니다!

2024-03-22 15:10 UTC, hhhhhwi commented on src/main/java/nextstep/subway/ui/controller/PathController.java
> +		}
loginMember에 null 여부를 확인하는 메소드를 생성하여 서비스 레이어에서 분기처리하도록 수정해보았습니다!

2024-03-22 15:11 UTC, hhhhhwi commented
성현님 꼼꼼한 피드백 감사합니다..!

일정 상 너무 늦게.. 추가 피드백을 계속 드리는 것 같아 죄송할 따름입니다 ㅠ

2024-03-25 01:21 UTC, boorownie approved these changes
피드백 반영 확인했습니다!
끝까지 미션 수행하시느라 고생 많으셨어요!
이번 과정과 미션이 휘연님의 성장에 도움이 되셨길 바랍니다.

미션 머지할게요~

2024-03-25 01:21 UTC, boorownie commented on src/main/java/nextstep/subway/application/service/PathService.java
> +		return createPathResponse(path, type, new FareCalculator(path).getFare());
피드백 반영 잘 해주셨어요!
제가 기대했던 부분은 널 오브젝트 패턴을 활용해서 구현하는 것이였어요!
member의 널 오브젝트 객체를 만들어 `getFare`를 호출하면 나이와 상관없이 기본 요금이 응답되도록 하는 형태였습니다 :)

2024-03-25 01:21 UTC, boorownie commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +		Long id = getLineId(createResponse);
:)

2024-03-25 01:21 UTC, boorownie commented on src/main/java/nextstep/subway/domain/fare/FareCalculator.java
> +            fare = (int) policy.applyDiscountPercent(fare);
가독성이 많이 개선된 것 같아요!

2024-03-25 01:21 UTC, merged