1단계 - 경로 조회 타입 추가
next-step/atdd-subway-time pull request #495
Opened 2024-08-06 14:10 UTC by pilming44

안녕하세요 이번 미션 리뷰이 최재현입니다!
지난주 강의에서 강사님이 기능 수정할때 기존의 기능은 보장하면서 점진적인 리팩토링을 한다고 하셔서
임시 클래스들을 전부 만들어서 구현했는데요
물리적으로 너무 많을 작업을 해야돼서.. 과연 이렇게 하는게 맞는것인지...의문이 듭니다..
그냥 브랜치를 따서 할걸그랬나봐요 ㅠ^ㅠ 제가 노하우가 없어서 너무 무식하게 한걸수도있습니다.. 흑..
리뷰 잘 부탁드립니다!

2024-08-07 12:54 UTC, seondongpyo requested changes
안녕하세요, 재현님. 마지막 미션을 함께하게 된 표선동이라고 합니다.
1단계 미션 잘 구현해주셨네요 👍 
몇 가지 코멘트 드렸는데 확인 후 다시 리뷰 요청을 부탁 드리겠습니다 🔥

2024-08-07 12:54 UTC, seondongpyo commented on src/test/java/nextstep/cucumber/steps/PathStepDef.java
> +    }
`@When`이 선언된 메서드들 아래로 옮겨보면 `When-Then` 순으로 읽기가 더 편해질 것 같습니다.

2024-08-07 12:54 UTC, seondongpyo commented on src/test/resources/features/path.feature
> +  Background: 지하철 노선도 준비
DataTable 활용 👍

2024-08-07 12:54 UTC, seondongpyo commented on src/test/java/nextstep/cucumber/steps/LineStepDef.java
> +                            .extract();
`AcceptanceTestUtil`에 정의해두신 메서드를 활용해 볼 수 없을까요? 지금처럼 `RestAssured`를 통해 각각의 API를 호출하는 로직들을 메서드로 잘 정의해두신다면 편하게 테스트를 작성하실 수 있지 않을까 생각합니다.
```suggestion
                    ExtractableResponse<Response> response = AcceptanceTestUtil.노선_생성_Extract(params);
```

2024-08-07 12:54 UTC, seondongpyo commented on src/main/java/nextstep/subway/auth/application/UserTokenServiceProvider.java
> +    }
객체지향 생활 체조 원칙 `규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.` 항목을 참고해주세요.

2024-08-07 12:54 UTC, seondongpyo commented on src/main/java/nextstep/subway/member/application/MemberService.java
> +                .orElseThrow(() -> new NoSuchMemberException("존재하지 않는 사용자입니다."));
예외 메시지가 중복으로 작성되어 있는데, 예외 메시지를 예외 클래스 내부로 옮겨보는 건 어떨까요?

2024-08-07 12:54 UTC, seondongpyo commented on src/main/java/nextstep/subway/member/application/MemberService.java
> +}
파일의 끝에는 개행을 추가해보면 어떨까요?
https://velog.io/@doondoony/posix-eol

2024-08-07 12:54 UTC, seondongpyo commented on src/main/java/nextstep/subway/path/domain/CustomWeightedEdge.java
> +        if (type == PathSearchType.DURATION) {
값을 비교하는 대신에 메시지를 보내는 방식으로 변경해보면 어떨까요?
```suggestion
        if (type.isDistance()) {
```

2024-08-07 12:54 UTC, seondongpyo commented on src/main/java/nextstep/subway/path/domain/PathFinderBuilder.java
> +                .forEach(s -> {
아래처럼 바로 `forEach()`를 호출해볼 수도 있을 것 같아요.
```suggestion
        sections.forEach(s -> {
```

2024-08-07 12:54 UTC, seondongpyo commented on src/main/java/nextstep/subway/path/domain/DijkstraShortestPathFinder.java
> +    }
해당 메서드들을 `static` 메서드로 선언해주신 이유가 있으실까요?

2024-08-07 12:54 UTC, seondongpyo commented on src/test/java/nextstep/subway/path/domain/DijkstraShortestPathFinderTest.java
> +        삼호선.addSection(남부터미널역, 양재역, 3L, 5L);
테스트에 필요한 데이터를 준비하는 동일한 코드가 반복적으로 보이는데, 코드 중복을 줄여보면 어떨까요?

2024-08-08 06:53 UTC, pilming44 commented
매번 리뷰어님들의 꼼꼼한 리뷰에 감탄합니다..
리뷰내용을 바탕으로 다시 한번 수정해봤습니다!
감사합니다!

2024-08-08 06:53 UTC, pilming44 commented on src/main/java/nextstep/subway/path/domain/DijkstraShortestPathFinder.java
> +    }
구현하면서 이렇게 저렇게 해보다가 남은 코드 같습니다.. 없앴습니다!!

2024-08-08 23:26 UTC, seondongpyo approved these changes
피드백 잘 반영해주셨네요 👍 
이번 단계는 여기서 merge 하겠습니다.
다음 단계에서 뵐게요 🔥

2024-08-08 23:26 UTC, seondongpyo commented on src/main/java/nextstep/subway/path/application/dto/PathSearchType.java
> +        return this.equals(DURATION);
Nit: 열거형 상수는 싱글턴 인스턴스이기 때문에, `==`으로 비교할 수도 있습니다.
```suggestion
        return this == DURATION;
```

2024-08-08 23:26 UTC, merged