2단계 - 요금 조회
next-step/atdd-subway-time pull request #502
Opened 2024-08-11 12:10 UTC by jin-mook

안녕하세요 정진묵입니다.

2단계 미션 피드백 부탁드립니다.

Path 도메인에서 요금 조회 기능을 구현할 때 요금 정책과 요금을 계산해주는 기능을 하는 PaymentPolicy 라는 인터페이스를 만들어서 진행했습니다.
이때 해당 인터페이스의 구현체를 보면 겹치는 메서드와 겹치는 필드들이 있습니다.
계속 겹치는 부분이 생기다 보니 DefaultPolicy 클래스로 만들어서 상속으로 구현할지 고민했는데, 개인적으로 상속보다는 인터페이스를 구현하는걸 선호하다보니 계속 겹치는 부분이 생기는것 같습니다.

리뷰어님은 이런 경우 상속이나 인터페이스 중에 어떤걸 더 선호하시나요?? 혹은 좀 더 괜찮은 방법이 있을까요??

이번 미션도 잘 부탁드립니다!!
감사합니다~~

2024-08-12 12:09 UTC, heoseungyeon requested changes
안녕하세요 진묵님 🙇 
2단계 미션도 빠르게 잘 수행해주셨네요 👍 
커멘트 드린 부분 있는데 한번 확인해주시고 다시 리뷰 유청 부탁드리겠습니다 :)

2024-08-12 12:09 UTC, dia312 commented on src/main/java/nextstep/subway/path/domain/OverFifthPaymentPolicy.java
> +    private static final int DEFAULT_DISTANCE_FEE = 100;
매직 넘버를 의미를 파악하기 쉽게 상수화를 잘 해주셨네요 👍

2024-08-12 12:09 UTC, heoseungyeon commented on src/main/java/nextstep/subway/path/domain/Path.java
> +    private static final int DEFAULT_PAYMENT = 1250;
해당 값들을 XXXPolicy 에서 공통으로 사용할 수 있게 변경하면 재사용성을 높일 수 있을거에요 😄

2024-08-12 12:09 UTC, heoseungyeon commented on src/main/java/nextstep/subway/path/domain/Path.java
> +    private int payment;
`setPayment()` 의 요금 산정 정책을 선택하고 요금을 정책에 맞게 계산하는 로직을 
Path 도메인이 아닌 `Payment` 객체에 두면 도메인 간 결합도가 느슨해질 수 있을거에요! Payment 객체를 Enum으로 활용할 경우 `IntPredicate`, `IntFunction` 과 같은 함수형 인터페이스를 멤버 변수로 사용해보는 것을 추천드립니다 !

2024-08-12 12:09 UTC, heoseungyeon commented on src/test/java/nextstep/subway/path/domain/PathTest.java
> +    }
`@ParameterizedTest`를 통해 다양한 케이스들에 대한 테스트를 진행해주셨네요 👍

2024-08-12 12:31 UTC, heoseungyeon commented
> Path 도메인에서 요금 조회 기능을 구현할 때 요금 정책과 요금을 계산해주는 기능을 하는 PaymentPolicy 라는 인터페이스를 만들어서 진행했습니다. 이때 해당 인터페이스의 구현체를 보면 겹치는 메서드와 겹치는 필드들이 있습니다. 계속 겹치는 부분이 생기다 보니 DefaultPolicy 클래스로 만들어서 상속으로 구현할지 고민했는데, 개인적으로 상속보다는 인터페이스를 구현하는걸 선호하다보니 계속 겹치는 부분이 생기는것 같습니다.
> 
> 리뷰어님은 이런 경우 상속이나 인터페이스 중에 어떤걸 더 선호하시나요?? 혹은 좀 더 괜찮은 방법이 있을까요??

요금에 대한 정책(PaymentPolicy)에 두 행위(요금 정책 산정, 요금 계산)를 정의했을 때, 이 두 행위에 대한 구현은 A, B, C 각 객체에 맡기고 객체 간 결합도를 최소화시키기 위해 인터페이스를 사용하는 것을 더 선호하는 편이에요. 
또 겹치는 필드들은 다른 객체를 활용하여 줄여볼 수 있겠고, 겹치는 메서드들은 인터페이스를 구현하기 위해선 어쩔 수 없는거라 생각이 드네요 🥲

2024-08-12 12:35 UTC, jin-mook commented on src/main/java/nextstep/subway/path/domain/Path.java
> +    private static final int DEFAULT_PAYMENT = 1250;
앗, Path 에 존재하는 위 변수들을 처음에 Path 에 구현해서 존재했는데 이후 XXXPolicy 인터페이스의 각 구현체에 따로 두었는데 지우는걸 깜박했네요 ㅠㅠ
감사합니다!!

2024-08-12 13:02 UTC, jin-mook commented on src/main/java/nextstep/subway/path/domain/Path.java
> +    private int payment;
피드백 감사합니다!! 처음에 private int payment 도 Value Object로 만들까 고민을 했다가 로직이 많지 않을거라고 생각해서 int 로 만들었는데, 말씀하신대로 객체로 만드니 훨씬 객체간 결합도가 느슨해지고, 테스트할때도 더 목적에 맞는 클래스에 대해 테스트한다고 느꼈습니다. 감사합니다~~

Payment 객체를 Enum 으로 활용하는 경우에 대해 말씀해주셨는데, 개인적으로 여기서는 각 요금 정책마다 필요로 하는 변수도 다르고 로직도 달라질 수 있다고 생각해서, Enum 보다는 기존처럼 클래스로 만드는게 변화에 대응하기 좀 더 좋지 않을까 라는 생각을 했습니다.

혹시 리뷰어님께서 Enum 이 더 괜찮을것 같다고 다시 말씀해주시면 바로 수정하도록 하겠습니다!!

감사합니다~~

2024-08-12 13:04 UTC, jin-mook commented
> 요금에 대한 정책(PaymentPolicy)에 두 행위(요금 정책 산정, 요금 계산)를 정의했을 때, 이 두 행위에 대한 구현은 A, B, C 각 객체에 맡기고 객체 간 결합도를 최소화시키기 위해 인터페이스를 사용하는 것을 더 선호하는 편이에요. 또 겹치는 필드들은 다른 객체를 활용하여 줄여볼 수 있겠고, 겹치는 메서드들은 인터페이스를 구현하기 위해선 어쩔 수 없는거라 생각이 드네요 🥲

자세히 설명해주셔서 감사합니다!! 스스로 좀 정리가 된 것 같습니다!!
감사합니다~~

2024-08-12 13:26 UTC, heoseungyeon commented on src/main/java/nextstep/subway/path/domain/Path.java
> +    private int payment;
> 개인적으로 여기서는 각 요금 정책마다 필요로 하는 변수도 다르고 로직도 달라질 수 있다고 생각해서, Enum 보다는 기존처럼 클래스로 만드는게 변화에 대응하기 좀 더 좋지 않을까

진묵님께서 말씀해주신 이 부분이 Enum을 사용하는 것보다 Class 를 사용하는 이유에 대해 잘 설명해주신 것 같아요 💯 💯

2024-08-12 13:53 UTC, heoseungyeon approved these changes
진묵님! 빠르게 피드백 반영 잘 해주셨네요 👍 👍 
간단한 커멘트 남긴 부분만 확인해주시고 바로 다음 단계 이어서 진행해주시면 됩니다 !
다음 단계도 화이팅입니다 🔥 🔥

2024-08-12 13:53 UTC, heoseungyeon commented on src/main/java/nextstep/subway/path/domain/PaymentPolicyConstant.java
> +}
👍 👍

2024-08-12 13:53 UTC, heoseungyeon commented on src/main/java/nextstep/subway/path/domain/Payment.java
> +    }
개인적으로 생성자에 멤버 변수가 아닌 다른 필드 값을 넣으면 추후에 헷갈릴 우려가 있어 지양하는 편인데요, 
아래와 같이 해볼 수 있을 것 같은데 진묵님 생각은 어때요?
```suggestion
    private Payment(long payment) {
        this.payment = setPayment(payment);
    }
        
     public static Payment of(long distance) {
         return this.Payment(calculate(distance));
     }
    
```

2024-08-12 13:53 UTC, merged

2024-08-14 06:58 UTC, jin-mook commented on src/main/java/nextstep/subway/path/domain/Payment.java
> +    }
피드백 감사합니다!!
사실 저도 정적 메서드를 이용해서 객체 생성을 자주 하는 편인데, 저는 기존에는 생성할 때 의미가 있는 이름을 사용하기 위한 목적으로 주로 사용했습니다.
이번에 리뷰어님께서 말씀해주신 서로 다른 필드 값을 넣을때 사용하는것도 굉장히 좋다고 느껴서 수정했습니다!!
애매하게 있던 저의 기준이 좀 더 명확하게 정리된것 같아요!!

좋은 피드백 주셔서 감사합니다~~